// Generated by gencpp from file web_monitor2/sendGoalPose.msg
// DO NOT EDIT!


#ifndef WEB_MONITOR2_MESSAGE_SENDGOALPOSE_H
#define WEB_MONITOR2_MESSAGE_SENDGOALPOSE_H

#include <ros/service_traits.h>


#include <web_monitor2/sendGoalPoseRequest.h>
#include <web_monitor2/sendGoalPoseResponse.h>


namespace web_monitor2
{

struct sendGoalPose
{

typedef sendGoalPoseRequest Request;
typedef sendGoalPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct sendGoalPose
} // namespace web_monitor2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::web_monitor2::sendGoalPose > {
  static const char* value()
  {
    return "cd2c26734e978127e0e9c0f2b353125a";
  }

  static const char* value(const ::web_monitor2::sendGoalPose&) { return value(); }
};

template<>
struct DataType< ::web_monitor2::sendGoalPose > {
  static const char* value()
  {
    return "web_monitor2/sendGoalPose";
  }

  static const char* value(const ::web_monitor2::sendGoalPose&) { return value(); }
};


// service_traits::MD5Sum< ::web_monitor2::sendGoalPoseRequest> should match 
// service_traits::MD5Sum< ::web_monitor2::sendGoalPose > 
template<>
struct MD5Sum< ::web_monitor2::sendGoalPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::web_monitor2::sendGoalPose >::value();
  }
  static const char* value(const ::web_monitor2::sendGoalPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::web_monitor2::sendGoalPoseRequest> should match 
// service_traits::DataType< ::web_monitor2::sendGoalPose > 
template<>
struct DataType< ::web_monitor2::sendGoalPoseRequest>
{
  static const char* value()
  {
    return DataType< ::web_monitor2::sendGoalPose >::value();
  }
  static const char* value(const ::web_monitor2::sendGoalPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::web_monitor2::sendGoalPoseResponse> should match 
// service_traits::MD5Sum< ::web_monitor2::sendGoalPose > 
template<>
struct MD5Sum< ::web_monitor2::sendGoalPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::web_monitor2::sendGoalPose >::value();
  }
  static const char* value(const ::web_monitor2::sendGoalPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::web_monitor2::sendGoalPoseResponse> should match 
// service_traits::DataType< ::web_monitor2::sendGoalPose > 
template<>
struct DataType< ::web_monitor2::sendGoalPoseResponse>
{
  static const char* value()
  {
    return DataType< ::web_monitor2::sendGoalPose >::value();
  }
  static const char* value(const ::web_monitor2::sendGoalPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WEB_MONITOR2_MESSAGE_SENDGOALPOSE_H
