// Generated by gencpp from file web_monitor2/sendGoalPoseResponse.msg
// DO NOT EDIT!


#ifndef WEB_MONITOR2_MESSAGE_SENDGOALPOSERESPONSE_H
#define WEB_MONITOR2_MESSAGE_SENDGOALPOSERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace web_monitor2
{
template <class ContainerAllocator>
struct sendGoalPoseResponse_
{
  typedef sendGoalPoseResponse_<ContainerAllocator> Type;

  sendGoalPoseResponse_()
    : status(0)  {
    }
  sendGoalPoseResponse_(const ContainerAllocator& _alloc)
    : status(0)  {
  (void)_alloc;
    }



   typedef int64_t _status_type;
  _status_type status;




  typedef boost::shared_ptr< ::web_monitor2::sendGoalPoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::web_monitor2::sendGoalPoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct sendGoalPoseResponse_

typedef ::web_monitor2::sendGoalPoseResponse_<std::allocator<void> > sendGoalPoseResponse;

typedef boost::shared_ptr< ::web_monitor2::sendGoalPoseResponse > sendGoalPoseResponsePtr;
typedef boost::shared_ptr< ::web_monitor2::sendGoalPoseResponse const> sendGoalPoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::web_monitor2::sendGoalPoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::web_monitor2::sendGoalPoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace web_monitor2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::web_monitor2::sendGoalPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::web_monitor2::sendGoalPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::web_monitor2::sendGoalPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::web_monitor2::sendGoalPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::web_monitor2::sendGoalPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::web_monitor2::sendGoalPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::web_monitor2::sendGoalPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4107476a6271fc2684d94be17d33f854";
  }

  static const char* value(const ::web_monitor2::sendGoalPoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4107476a6271fc26ULL;
  static const uint64_t static_value2 = 0x84d94be17d33f854ULL;
};

template<class ContainerAllocator>
struct DataType< ::web_monitor2::sendGoalPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "web_monitor2/sendGoalPoseResponse";
  }

  static const char* value(const ::web_monitor2::sendGoalPoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::web_monitor2::sendGoalPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 status\n\
\n\
";
  }

  static const char* value(const ::web_monitor2::sendGoalPoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::web_monitor2::sendGoalPoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sendGoalPoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::web_monitor2::sendGoalPoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::web_monitor2::sendGoalPoseResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<int64_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WEB_MONITOR2_MESSAGE_SENDGOALPOSERESPONSE_H
