// Generated by gencpp from file neo_msgs/JointCurrent.msg
// DO NOT EDIT!


#ifndef NEO_MSGS_MESSAGE_JOINTCURRENT_H
#define NEO_MSGS_MESSAGE_JOINTCURRENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace neo_msgs
{
template <class ContainerAllocator>
struct JointCurrent_
{
  typedef JointCurrent_<ContainerAllocator> Type;

  JointCurrent_()
    : current()  {
    }
  JointCurrent_(const ContainerAllocator& _alloc)
    : current(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _current_type;
  _current_type current;




  typedef boost::shared_ptr< ::neo_msgs::JointCurrent_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::neo_msgs::JointCurrent_<ContainerAllocator> const> ConstPtr;

}; // struct JointCurrent_

typedef ::neo_msgs::JointCurrent_<std::allocator<void> > JointCurrent;

typedef boost::shared_ptr< ::neo_msgs::JointCurrent > JointCurrentPtr;
typedef boost::shared_ptr< ::neo_msgs::JointCurrent const> JointCurrentConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::neo_msgs::JointCurrent_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::neo_msgs::JointCurrent_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace neo_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'neo_msgs': ['/home/eaibot/dashgo_ws/src/neocobot/neo_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::neo_msgs::JointCurrent_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::neo_msgs::JointCurrent_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neo_msgs::JointCurrent_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neo_msgs::JointCurrent_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neo_msgs::JointCurrent_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neo_msgs::JointCurrent_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::neo_msgs::JointCurrent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1634c573362b3eca9589d81d03b20094";
  }

  static const char* value(const ::neo_msgs::JointCurrent_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1634c573362b3ecaULL;
  static const uint64_t static_value2 = 0x9589d81d03b20094ULL;
};

template<class ContainerAllocator>
struct DataType< ::neo_msgs::JointCurrent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "neo_msgs/JointCurrent";
  }

  static const char* value(const ::neo_msgs::JointCurrent_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::neo_msgs::JointCurrent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] current\n\
";
  }

  static const char* value(const ::neo_msgs::JointCurrent_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::neo_msgs::JointCurrent_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointCurrent_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::neo_msgs::JointCurrent_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::neo_msgs::JointCurrent_<ContainerAllocator>& v)
  {
    s << indent << "current[]" << std::endl;
    for (size_t i = 0; i < v.current.size(); ++i)
    {
      s << indent << "  current[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.current[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NEO_MSGS_MESSAGE_JOINTCURRENT_H
