// Generated by gencpp from file neo_msgs/MoveToPoseRequest.msg
// DO NOT EDIT!


#ifndef NEO_MSGS_MESSAGE_MOVETOPOSEREQUEST_H
#define NEO_MSGS_MESSAGE_MOVETOPOSEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <neo_msgs/EndPose.h>

namespace neo_msgs
{
template <class ContainerAllocator>
struct MoveToPoseRequest_
{
  typedef MoveToPoseRequest_<ContainerAllocator> Type;

  MoveToPoseRequest_()
    : pose()
    , velocity(0.0)
    , acceleration(0.0)
    , relative(false)
    , block(false)  {
    }
  MoveToPoseRequest_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , velocity(0.0)
    , acceleration(0.0)
    , relative(false)
    , block(false)  {
  (void)_alloc;
    }



   typedef  ::neo_msgs::EndPose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef float _velocity_type;
  _velocity_type velocity;

   typedef float _acceleration_type;
  _acceleration_type acceleration;

   typedef uint8_t _relative_type;
  _relative_type relative;

   typedef uint8_t _block_type;
  _block_type block;




  typedef boost::shared_ptr< ::neo_msgs::MoveToPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::neo_msgs::MoveToPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoveToPoseRequest_

typedef ::neo_msgs::MoveToPoseRequest_<std::allocator<void> > MoveToPoseRequest;

typedef boost::shared_ptr< ::neo_msgs::MoveToPoseRequest > MoveToPoseRequestPtr;
typedef boost::shared_ptr< ::neo_msgs::MoveToPoseRequest const> MoveToPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::neo_msgs::MoveToPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::neo_msgs::MoveToPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace neo_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'neo_msgs': ['/home/eaibot/dashgo_ws/src/neocobot/neo_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::neo_msgs::MoveToPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::neo_msgs::MoveToPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neo_msgs::MoveToPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neo_msgs::MoveToPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neo_msgs::MoveToPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neo_msgs::MoveToPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::neo_msgs::MoveToPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9c345ad7293a476b4ba0628ca88f3694";
  }

  static const char* value(const ::neo_msgs::MoveToPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9c345ad7293a476bULL;
  static const uint64_t static_value2 = 0x4ba0628ca88f3694ULL;
};

template<class ContainerAllocator>
struct DataType< ::neo_msgs::MoveToPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "neo_msgs/MoveToPoseRequest";
  }

  static const char* value(const ::neo_msgs::MoveToPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::neo_msgs::MoveToPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "EndPose pose\n\
float32 velocity\n\
float32 acceleration\n\
bool relative\n\
bool block\n\
\n\
================================================================================\n\
MSG: neo_msgs/EndPose\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 Rx\n\
float64 Ry\n\
float64 Rz\n\
";
  }

  static const char* value(const ::neo_msgs::MoveToPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::neo_msgs::MoveToPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.velocity);
      stream.next(m.acceleration);
      stream.next(m.relative);
      stream.next(m.block);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveToPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::neo_msgs::MoveToPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::neo_msgs::MoveToPoseRequest_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::neo_msgs::EndPose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "velocity: ";
    Printer<float>::stream(s, indent + "  ", v.velocity);
    s << indent << "acceleration: ";
    Printer<float>::stream(s, indent + "  ", v.acceleration);
    s << indent << "relative: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.relative);
    s << indent << "block: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.block);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NEO_MSGS_MESSAGE_MOVETOPOSEREQUEST_H
