// Generated by gencpp from file neo_msgs/MoveToAnglesRequest.msg
// DO NOT EDIT!


#ifndef NEO_MSGS_MESSAGE_MOVETOANGLESREQUEST_H
#define NEO_MSGS_MESSAGE_MOVETOANGLESREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace neo_msgs
{
template <class ContainerAllocator>
struct MoveToAnglesRequest_
{
  typedef MoveToAnglesRequest_<ContainerAllocator> Type;

  MoveToAnglesRequest_()
    : motor_ids()
    , angles()
    , velocity(0.0)
    , acceleration(0.0)
    , relative(false)
    , block(false)  {
    }
  MoveToAnglesRequest_(const ContainerAllocator& _alloc)
    : motor_ids(_alloc)
    , angles(_alloc)
    , velocity(0.0)
    , acceleration(0.0)
    , relative(false)
    , block(false)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _motor_ids_type;
  _motor_ids_type motor_ids;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _angles_type;
  _angles_type angles;

   typedef float _velocity_type;
  _velocity_type velocity;

   typedef float _acceleration_type;
  _acceleration_type acceleration;

   typedef uint8_t _relative_type;
  _relative_type relative;

   typedef uint8_t _block_type;
  _block_type block;




  typedef boost::shared_ptr< ::neo_msgs::MoveToAnglesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::neo_msgs::MoveToAnglesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoveToAnglesRequest_

typedef ::neo_msgs::MoveToAnglesRequest_<std::allocator<void> > MoveToAnglesRequest;

typedef boost::shared_ptr< ::neo_msgs::MoveToAnglesRequest > MoveToAnglesRequestPtr;
typedef boost::shared_ptr< ::neo_msgs::MoveToAnglesRequest const> MoveToAnglesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::neo_msgs::MoveToAnglesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::neo_msgs::MoveToAnglesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace neo_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'neo_msgs': ['/home/eaibot/dashgo_ws/src/neocobot/neo_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::neo_msgs::MoveToAnglesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::neo_msgs::MoveToAnglesRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neo_msgs::MoveToAnglesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neo_msgs::MoveToAnglesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neo_msgs::MoveToAnglesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neo_msgs::MoveToAnglesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::neo_msgs::MoveToAnglesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36e0733c6aa70456810eb19b39c1dd3b";
  }

  static const char* value(const ::neo_msgs::MoveToAnglesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36e0733c6aa70456ULL;
  static const uint64_t static_value2 = 0x810eb19b39c1dd3bULL;
};

template<class ContainerAllocator>
struct DataType< ::neo_msgs::MoveToAnglesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "neo_msgs/MoveToAnglesRequest";
  }

  static const char* value(const ::neo_msgs::MoveToAnglesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::neo_msgs::MoveToAnglesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] motor_ids\n\
float64[] angles\n\
float32 velocity\n\
float32 acceleration\n\
bool relative\n\
bool block\n\
";
  }

  static const char* value(const ::neo_msgs::MoveToAnglesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::neo_msgs::MoveToAnglesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motor_ids);
      stream.next(m.angles);
      stream.next(m.velocity);
      stream.next(m.acceleration);
      stream.next(m.relative);
      stream.next(m.block);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveToAnglesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::neo_msgs::MoveToAnglesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::neo_msgs::MoveToAnglesRequest_<ContainerAllocator>& v)
  {
    s << indent << "motor_ids[]" << std::endl;
    for (size_t i = 0; i < v.motor_ids.size(); ++i)
    {
      s << indent << "  motor_ids[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.motor_ids[i]);
    }
    s << indent << "angles[]" << std::endl;
    for (size_t i = 0; i < v.angles.size(); ++i)
    {
      s << indent << "  angles[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.angles[i]);
    }
    s << indent << "velocity: ";
    Printer<float>::stream(s, indent + "  ", v.velocity);
    s << indent << "acceleration: ";
    Printer<float>::stream(s, indent + "  ", v.acceleration);
    s << indent << "relative: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.relative);
    s << indent << "block: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.block);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NEO_MSGS_MESSAGE_MOVETOANGLESREQUEST_H
