// Generated by gencpp from file neo_msgs/MoveToPose.msg
// DO NOT EDIT!


#ifndef NEO_MSGS_MESSAGE_MOVETOPOSE_H
#define NEO_MSGS_MESSAGE_MOVETOPOSE_H

#include <ros/service_traits.h>


#include <neo_msgs/MoveToPoseRequest.h>
#include <neo_msgs/MoveToPoseResponse.h>


namespace neo_msgs
{

struct MoveToPose
{

typedef MoveToPoseRequest Request;
typedef MoveToPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveToPose
} // namespace neo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::neo_msgs::MoveToPose > {
  static const char* value()
  {
    return "550b9435c70b6cfbf9422fec504e8a70";
  }

  static const char* value(const ::neo_msgs::MoveToPose&) { return value(); }
};

template<>
struct DataType< ::neo_msgs::MoveToPose > {
  static const char* value()
  {
    return "neo_msgs/MoveToPose";
  }

  static const char* value(const ::neo_msgs::MoveToPose&) { return value(); }
};


// service_traits::MD5Sum< ::neo_msgs::MoveToPoseRequest> should match 
// service_traits::MD5Sum< ::neo_msgs::MoveToPose > 
template<>
struct MD5Sum< ::neo_msgs::MoveToPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::neo_msgs::MoveToPose >::value();
  }
  static const char* value(const ::neo_msgs::MoveToPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::neo_msgs::MoveToPoseRequest> should match 
// service_traits::DataType< ::neo_msgs::MoveToPose > 
template<>
struct DataType< ::neo_msgs::MoveToPoseRequest>
{
  static const char* value()
  {
    return DataType< ::neo_msgs::MoveToPose >::value();
  }
  static const char* value(const ::neo_msgs::MoveToPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::neo_msgs::MoveToPoseResponse> should match 
// service_traits::MD5Sum< ::neo_msgs::MoveToPose > 
template<>
struct MD5Sum< ::neo_msgs::MoveToPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::neo_msgs::MoveToPose >::value();
  }
  static const char* value(const ::neo_msgs::MoveToPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::neo_msgs::MoveToPoseResponse> should match 
// service_traits::DataType< ::neo_msgs::MoveToPose > 
template<>
struct DataType< ::neo_msgs::MoveToPoseResponse>
{
  static const char* value()
  {
    return DataType< ::neo_msgs::MoveToPose >::value();
  }
  static const char* value(const ::neo_msgs::MoveToPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NEO_MSGS_MESSAGE_MOVETOPOSE_H
