// Generated by gencpp from file neo_msgs/Recover.msg
// DO NOT EDIT!


#ifndef NEO_MSGS_MESSAGE_RECOVER_H
#define NEO_MSGS_MESSAGE_RECOVER_H

#include <ros/service_traits.h>


#include <neo_msgs/RecoverRequest.h>
#include <neo_msgs/RecoverResponse.h>


namespace neo_msgs
{

struct Recover
{

typedef RecoverRequest Request;
typedef RecoverResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Recover
} // namespace neo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::neo_msgs::Recover > {
  static const char* value()
  {
    return "b2a9c605bb7a420089b02c6063322298";
  }

  static const char* value(const ::neo_msgs::Recover&) { return value(); }
};

template<>
struct DataType< ::neo_msgs::Recover > {
  static const char* value()
  {
    return "neo_msgs/Recover";
  }

  static const char* value(const ::neo_msgs::Recover&) { return value(); }
};


// service_traits::MD5Sum< ::neo_msgs::RecoverRequest> should match 
// service_traits::MD5Sum< ::neo_msgs::Recover > 
template<>
struct MD5Sum< ::neo_msgs::RecoverRequest>
{
  static const char* value()
  {
    return MD5Sum< ::neo_msgs::Recover >::value();
  }
  static const char* value(const ::neo_msgs::RecoverRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::neo_msgs::RecoverRequest> should match 
// service_traits::DataType< ::neo_msgs::Recover > 
template<>
struct DataType< ::neo_msgs::RecoverRequest>
{
  static const char* value()
  {
    return DataType< ::neo_msgs::Recover >::value();
  }
  static const char* value(const ::neo_msgs::RecoverRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::neo_msgs::RecoverResponse> should match 
// service_traits::MD5Sum< ::neo_msgs::Recover > 
template<>
struct MD5Sum< ::neo_msgs::RecoverResponse>
{
  static const char* value()
  {
    return MD5Sum< ::neo_msgs::Recover >::value();
  }
  static const char* value(const ::neo_msgs::RecoverResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::neo_msgs::RecoverResponse> should match 
// service_traits::DataType< ::neo_msgs::Recover > 
template<>
struct DataType< ::neo_msgs::RecoverResponse>
{
  static const char* value()
  {
    return DataType< ::neo_msgs::Recover >::value();
  }
  static const char* value(const ::neo_msgs::RecoverResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NEO_MSGS_MESSAGE_RECOVER_H
