// Generated by gencpp from file neo_msgs/Release.msg
// DO NOT EDIT!


#ifndef NEO_MSGS_MESSAGE_RELEASE_H
#define NEO_MSGS_MESSAGE_RELEASE_H

#include <ros/service_traits.h>


#include <neo_msgs/ReleaseRequest.h>
#include <neo_msgs/ReleaseResponse.h>


namespace neo_msgs
{

struct Release
{

typedef ReleaseRequest Request;
typedef ReleaseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Release
} // namespace neo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::neo_msgs::Release > {
  static const char* value()
  {
    return "1e3ab015e243c7706c372ab529619c93";
  }

  static const char* value(const ::neo_msgs::Release&) { return value(); }
};

template<>
struct DataType< ::neo_msgs::Release > {
  static const char* value()
  {
    return "neo_msgs/Release";
  }

  static const char* value(const ::neo_msgs::Release&) { return value(); }
};


// service_traits::MD5Sum< ::neo_msgs::ReleaseRequest> should match 
// service_traits::MD5Sum< ::neo_msgs::Release > 
template<>
struct MD5Sum< ::neo_msgs::ReleaseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::neo_msgs::Release >::value();
  }
  static const char* value(const ::neo_msgs::ReleaseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::neo_msgs::ReleaseRequest> should match 
// service_traits::DataType< ::neo_msgs::Release > 
template<>
struct DataType< ::neo_msgs::ReleaseRequest>
{
  static const char* value()
  {
    return DataType< ::neo_msgs::Release >::value();
  }
  static const char* value(const ::neo_msgs::ReleaseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::neo_msgs::ReleaseResponse> should match 
// service_traits::MD5Sum< ::neo_msgs::Release > 
template<>
struct MD5Sum< ::neo_msgs::ReleaseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::neo_msgs::Release >::value();
  }
  static const char* value(const ::neo_msgs::ReleaseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::neo_msgs::ReleaseResponse> should match 
// service_traits::DataType< ::neo_msgs::Release > 
template<>
struct DataType< ::neo_msgs::ReleaseResponse>
{
  static const char* value()
  {
    return DataType< ::neo_msgs::Release >::value();
  }
  static const char* value(const ::neo_msgs::ReleaseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NEO_MSGS_MESSAGE_RELEASE_H
