// Generated by gencpp from file neo_msgs/Reset.msg
// DO NOT EDIT!


#ifndef NEO_MSGS_MESSAGE_RESET_H
#define NEO_MSGS_MESSAGE_RESET_H

#include <ros/service_traits.h>


#include <neo_msgs/ResetRequest.h>
#include <neo_msgs/ResetResponse.h>


namespace neo_msgs
{

struct Reset
{

typedef ResetRequest Request;
typedef ResetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Reset
} // namespace neo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::neo_msgs::Reset > {
  static const char* value()
  {
    return "b2a9c605bb7a420089b02c6063322298";
  }

  static const char* value(const ::neo_msgs::Reset&) { return value(); }
};

template<>
struct DataType< ::neo_msgs::Reset > {
  static const char* value()
  {
    return "neo_msgs/Reset";
  }

  static const char* value(const ::neo_msgs::Reset&) { return value(); }
};


// service_traits::MD5Sum< ::neo_msgs::ResetRequest> should match 
// service_traits::MD5Sum< ::neo_msgs::Reset > 
template<>
struct MD5Sum< ::neo_msgs::ResetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::neo_msgs::Reset >::value();
  }
  static const char* value(const ::neo_msgs::ResetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::neo_msgs::ResetRequest> should match 
// service_traits::DataType< ::neo_msgs::Reset > 
template<>
struct DataType< ::neo_msgs::ResetRequest>
{
  static const char* value()
  {
    return DataType< ::neo_msgs::Reset >::value();
  }
  static const char* value(const ::neo_msgs::ResetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::neo_msgs::ResetResponse> should match 
// service_traits::MD5Sum< ::neo_msgs::Reset > 
template<>
struct MD5Sum< ::neo_msgs::ResetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::neo_msgs::Reset >::value();
  }
  static const char* value(const ::neo_msgs::ResetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::neo_msgs::ResetResponse> should match 
// service_traits::DataType< ::neo_msgs::Reset > 
template<>
struct DataType< ::neo_msgs::ResetResponse>
{
  static const char* value()
  {
    return DataType< ::neo_msgs::Reset >::value();
  }
  static const char* value(const ::neo_msgs::ResetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NEO_MSGS_MESSAGE_RESET_H
