// Generated by gencpp from file neo_msgs/SetEOATActionRequest.msg
// DO NOT EDIT!


#ifndef NEO_MSGS_MESSAGE_SETEOATACTIONREQUEST_H
#define NEO_MSGS_MESSAGE_SETEOATACTIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace neo_msgs
{
template <class ContainerAllocator>
struct SetEOATActionRequest_
{
  typedef SetEOATActionRequest_<ContainerAllocator> Type;

  SetEOATActionRequest_()
    : name()
    , action()  {
    }
  SetEOATActionRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , action(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _action_type;
  _action_type action;




  typedef boost::shared_ptr< ::neo_msgs::SetEOATActionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::neo_msgs::SetEOATActionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetEOATActionRequest_

typedef ::neo_msgs::SetEOATActionRequest_<std::allocator<void> > SetEOATActionRequest;

typedef boost::shared_ptr< ::neo_msgs::SetEOATActionRequest > SetEOATActionRequestPtr;
typedef boost::shared_ptr< ::neo_msgs::SetEOATActionRequest const> SetEOATActionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::neo_msgs::SetEOATActionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::neo_msgs::SetEOATActionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace neo_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'neo_msgs': ['/home/eaibot/dashgo_ws/src/neocobot/neo_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::neo_msgs::SetEOATActionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::neo_msgs::SetEOATActionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neo_msgs::SetEOATActionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neo_msgs::SetEOATActionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neo_msgs::SetEOATActionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neo_msgs::SetEOATActionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::neo_msgs::SetEOATActionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "04bf3f0359d6648551af1d59347795e7";
  }

  static const char* value(const ::neo_msgs::SetEOATActionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x04bf3f0359d66485ULL;
  static const uint64_t static_value2 = 0x51af1d59347795e7ULL;
};

template<class ContainerAllocator>
struct DataType< ::neo_msgs::SetEOATActionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "neo_msgs/SetEOATActionRequest";
  }

  static const char* value(const ::neo_msgs::SetEOATActionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::neo_msgs::SetEOATActionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
string action\n\
";
  }

  static const char* value(const ::neo_msgs::SetEOATActionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::neo_msgs::SetEOATActionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.action);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetEOATActionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::neo_msgs::SetEOATActionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::neo_msgs::SetEOATActionRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "action: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.action);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NEO_MSGS_MESSAGE_SETEOATACTIONREQUEST_H
