// Generated by gencpp from file neo_msgs/EndPose.msg
// DO NOT EDIT!


#ifndef NEO_MSGS_MESSAGE_ENDPOSE_H
#define NEO_MSGS_MESSAGE_ENDPOSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace neo_msgs
{
template <class ContainerAllocator>
struct EndPose_
{
  typedef EndPose_<ContainerAllocator> Type;

  EndPose_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , Rx(0.0)
    , Ry(0.0)
    , Rz(0.0)  {
    }
  EndPose_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , Rx(0.0)
    , Ry(0.0)
    , Rz(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _Rx_type;
  _Rx_type Rx;

   typedef double _Ry_type;
  _Ry_type Ry;

   typedef double _Rz_type;
  _Rz_type Rz;




  typedef boost::shared_ptr< ::neo_msgs::EndPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::neo_msgs::EndPose_<ContainerAllocator> const> ConstPtr;

}; // struct EndPose_

typedef ::neo_msgs::EndPose_<std::allocator<void> > EndPose;

typedef boost::shared_ptr< ::neo_msgs::EndPose > EndPosePtr;
typedef boost::shared_ptr< ::neo_msgs::EndPose const> EndPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::neo_msgs::EndPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::neo_msgs::EndPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace neo_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'neo_msgs': ['/home/eaibot/dashgo_ws/src/neocobot/neo_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::neo_msgs::EndPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::neo_msgs::EndPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neo_msgs::EndPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neo_msgs::EndPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neo_msgs::EndPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neo_msgs::EndPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::neo_msgs::EndPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9f62dbed28d2c842e4baf60dcb12c05c";
  }

  static const char* value(const ::neo_msgs::EndPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9f62dbed28d2c842ULL;
  static const uint64_t static_value2 = 0xe4baf60dcb12c05cULL;
};

template<class ContainerAllocator>
struct DataType< ::neo_msgs::EndPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "neo_msgs/EndPose";
  }

  static const char* value(const ::neo_msgs::EndPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::neo_msgs::EndPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n\
float64 y\n\
float64 z\n\
float64 Rx\n\
float64 Ry\n\
float64 Rz\n\
";
  }

  static const char* value(const ::neo_msgs::EndPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::neo_msgs::EndPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.Rx);
      stream.next(m.Ry);
      stream.next(m.Rz);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EndPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::neo_msgs::EndPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::neo_msgs::EndPose_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "Rx: ";
    Printer<double>::stream(s, indent + "  ", v.Rx);
    s << indent << "Ry: ";
    Printer<double>::stream(s, indent + "  ", v.Ry);
    s << indent << "Rz: ";
    Printer<double>::stream(s, indent + "  ", v.Rz);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NEO_MSGS_MESSAGE_ENDPOSE_H
