// Generated by gencpp from file neo_msgs/GetInputResponse.msg
// DO NOT EDIT!


#ifndef NEO_MSGS_MESSAGE_GETINPUTRESPONSE_H
#define NEO_MSGS_MESSAGE_GETINPUTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace neo_msgs
{
template <class ContainerAllocator>
struct GetInputResponse_
{
  typedef GetInputResponse_<ContainerAllocator> Type;

  GetInputResponse_()
    : event(0)
    , signal()  {
    }
  GetInputResponse_(const ContainerAllocator& _alloc)
    : event(0)
    , signal(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _event_type;
  _event_type event;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _signal_type;
  _signal_type signal;




  typedef boost::shared_ptr< ::neo_msgs::GetInputResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::neo_msgs::GetInputResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetInputResponse_

typedef ::neo_msgs::GetInputResponse_<std::allocator<void> > GetInputResponse;

typedef boost::shared_ptr< ::neo_msgs::GetInputResponse > GetInputResponsePtr;
typedef boost::shared_ptr< ::neo_msgs::GetInputResponse const> GetInputResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::neo_msgs::GetInputResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::neo_msgs::GetInputResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace neo_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'neo_msgs': ['/home/eaibot/dashgo_ws/src/neocobot/neo_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::neo_msgs::GetInputResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::neo_msgs::GetInputResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neo_msgs::GetInputResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neo_msgs::GetInputResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neo_msgs::GetInputResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neo_msgs::GetInputResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::neo_msgs::GetInputResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "149e43dd62200cd5a1ef6d9a23427937";
  }

  static const char* value(const ::neo_msgs::GetInputResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x149e43dd62200cd5ULL;
  static const uint64_t static_value2 = 0xa1ef6d9a23427937ULL;
};

template<class ContainerAllocator>
struct DataType< ::neo_msgs::GetInputResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "neo_msgs/GetInputResponse";
  }

  static const char* value(const ::neo_msgs::GetInputResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::neo_msgs::GetInputResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 event\n\
int32[] signal\n\
";
  }

  static const char* value(const ::neo_msgs::GetInputResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::neo_msgs::GetInputResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.event);
      stream.next(m.signal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetInputResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::neo_msgs::GetInputResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::neo_msgs::GetInputResponse_<ContainerAllocator>& v)
  {
    s << indent << "event: ";
    Printer<int32_t>::stream(s, indent + "  ", v.event);
    s << indent << "signal[]" << std::endl;
    for (size_t i = 0; i < v.signal.size(); ++i)
    {
      s << indent << "  signal[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.signal[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NEO_MSGS_MESSAGE_GETINPUTRESPONSE_H
