// Generated by gencpp from file neo_msgs/GetMotorIds.msg
// DO NOT EDIT!


#ifndef NEO_MSGS_MESSAGE_GETMOTORIDS_H
#define NEO_MSGS_MESSAGE_GETMOTORIDS_H

#include <ros/service_traits.h>


#include <neo_msgs/GetMotorIdsRequest.h>
#include <neo_msgs/GetMotorIdsResponse.h>


namespace neo_msgs
{

struct GetMotorIds
{

typedef GetMotorIdsRequest Request;
typedef GetMotorIdsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetMotorIds
} // namespace neo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::neo_msgs::GetMotorIds > {
  static const char* value()
  {
    return "da45074f03ccd6c00fa83c029210839d";
  }

  static const char* value(const ::neo_msgs::GetMotorIds&) { return value(); }
};

template<>
struct DataType< ::neo_msgs::GetMotorIds > {
  static const char* value()
  {
    return "neo_msgs/GetMotorIds";
  }

  static const char* value(const ::neo_msgs::GetMotorIds&) { return value(); }
};


// service_traits::MD5Sum< ::neo_msgs::GetMotorIdsRequest> should match 
// service_traits::MD5Sum< ::neo_msgs::GetMotorIds > 
template<>
struct MD5Sum< ::neo_msgs::GetMotorIdsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::neo_msgs::GetMotorIds >::value();
  }
  static const char* value(const ::neo_msgs::GetMotorIdsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::neo_msgs::GetMotorIdsRequest> should match 
// service_traits::DataType< ::neo_msgs::GetMotorIds > 
template<>
struct DataType< ::neo_msgs::GetMotorIdsRequest>
{
  static const char* value()
  {
    return DataType< ::neo_msgs::GetMotorIds >::value();
  }
  static const char* value(const ::neo_msgs::GetMotorIdsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::neo_msgs::GetMotorIdsResponse> should match 
// service_traits::MD5Sum< ::neo_msgs::GetMotorIds > 
template<>
struct MD5Sum< ::neo_msgs::GetMotorIdsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::neo_msgs::GetMotorIds >::value();
  }
  static const char* value(const ::neo_msgs::GetMotorIdsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::neo_msgs::GetMotorIdsResponse> should match 
// service_traits::DataType< ::neo_msgs::GetMotorIds > 
template<>
struct DataType< ::neo_msgs::GetMotorIdsResponse>
{
  static const char* value()
  {
    return DataType< ::neo_msgs::GetMotorIds >::value();
  }
  static const char* value(const ::neo_msgs::GetMotorIdsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NEO_MSGS_MESSAGE_GETMOTORIDS_H
