// Generated by gencpp from file neo_msgs/MoveP.msg
// DO NOT EDIT!


#ifndef NEO_MSGS_MESSAGE_MOVEP_H
#define NEO_MSGS_MESSAGE_MOVEP_H

#include <ros/service_traits.h>


#include <neo_msgs/MovePRequest.h>
#include <neo_msgs/MovePResponse.h>


namespace neo_msgs
{

struct MoveP
{

typedef MovePRequest Request;
typedef MovePResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveP
} // namespace neo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::neo_msgs::MoveP > {
  static const char* value()
  {
    return "c94ebec1f5e856eae9ca23929e46a5f8";
  }

  static const char* value(const ::neo_msgs::MoveP&) { return value(); }
};

template<>
struct DataType< ::neo_msgs::MoveP > {
  static const char* value()
  {
    return "neo_msgs/MoveP";
  }

  static const char* value(const ::neo_msgs::MoveP&) { return value(); }
};


// service_traits::MD5Sum< ::neo_msgs::MovePRequest> should match 
// service_traits::MD5Sum< ::neo_msgs::MoveP > 
template<>
struct MD5Sum< ::neo_msgs::MovePRequest>
{
  static const char* value()
  {
    return MD5Sum< ::neo_msgs::MoveP >::value();
  }
  static const char* value(const ::neo_msgs::MovePRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::neo_msgs::MovePRequest> should match 
// service_traits::DataType< ::neo_msgs::MoveP > 
template<>
struct DataType< ::neo_msgs::MovePRequest>
{
  static const char* value()
  {
    return DataType< ::neo_msgs::MoveP >::value();
  }
  static const char* value(const ::neo_msgs::MovePRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::neo_msgs::MovePResponse> should match 
// service_traits::MD5Sum< ::neo_msgs::MoveP > 
template<>
struct MD5Sum< ::neo_msgs::MovePResponse>
{
  static const char* value()
  {
    return MD5Sum< ::neo_msgs::MoveP >::value();
  }
  static const char* value(const ::neo_msgs::MovePResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::neo_msgs::MovePResponse> should match 
// service_traits::DataType< ::neo_msgs::MoveP > 
template<>
struct DataType< ::neo_msgs::MovePResponse>
{
  static const char* value()
  {
    return DataType< ::neo_msgs::MoveP >::value();
  }
  static const char* value(const ::neo_msgs::MovePResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NEO_MSGS_MESSAGE_MOVEP_H
