// Generated by gencpp from file neo_msgs/MoveJ.msg
// DO NOT EDIT!


#ifndef NEO_MSGS_MESSAGE_MOVEJ_H
#define NEO_MSGS_MESSAGE_MOVEJ_H

#include <ros/service_traits.h>


#include <neo_msgs/MoveJRequest.h>
#include <neo_msgs/MoveJResponse.h>


namespace neo_msgs
{

struct MoveJ
{

typedef MoveJRequest Request;
typedef MoveJResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveJ
} // namespace neo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::neo_msgs::MoveJ > {
  static const char* value()
  {
    return "c94ebec1f5e856eae9ca23929e46a5f8";
  }

  static const char* value(const ::neo_msgs::MoveJ&) { return value(); }
};

template<>
struct DataType< ::neo_msgs::MoveJ > {
  static const char* value()
  {
    return "neo_msgs/MoveJ";
  }

  static const char* value(const ::neo_msgs::MoveJ&) { return value(); }
};


// service_traits::MD5Sum< ::neo_msgs::MoveJRequest> should match 
// service_traits::MD5Sum< ::neo_msgs::MoveJ > 
template<>
struct MD5Sum< ::neo_msgs::MoveJRequest>
{
  static const char* value()
  {
    return MD5Sum< ::neo_msgs::MoveJ >::value();
  }
  static const char* value(const ::neo_msgs::MoveJRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::neo_msgs::MoveJRequest> should match 
// service_traits::DataType< ::neo_msgs::MoveJ > 
template<>
struct DataType< ::neo_msgs::MoveJRequest>
{
  static const char* value()
  {
    return DataType< ::neo_msgs::MoveJ >::value();
  }
  static const char* value(const ::neo_msgs::MoveJRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::neo_msgs::MoveJResponse> should match 
// service_traits::MD5Sum< ::neo_msgs::MoveJ > 
template<>
struct MD5Sum< ::neo_msgs::MoveJResponse>
{
  static const char* value()
  {
    return MD5Sum< ::neo_msgs::MoveJ >::value();
  }
  static const char* value(const ::neo_msgs::MoveJResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::neo_msgs::MoveJResponse> should match 
// service_traits::DataType< ::neo_msgs::MoveJ > 
template<>
struct DataType< ::neo_msgs::MoveJResponse>
{
  static const char* value()
  {
    return DataType< ::neo_msgs::MoveJ >::value();
  }
  static const char* value(const ::neo_msgs::MoveJResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NEO_MSGS_MESSAGE_MOVEJ_H
