// Generated by gencpp from file neo_msgs/Stop.msg
// DO NOT EDIT!


#ifndef NEO_MSGS_MESSAGE_STOP_H
#define NEO_MSGS_MESSAGE_STOP_H

#include <ros/service_traits.h>


#include <neo_msgs/StopRequest.h>
#include <neo_msgs/StopResponse.h>


namespace neo_msgs
{

struct Stop
{

typedef StopRequest Request;
typedef StopResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Stop
} // namespace neo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::neo_msgs::Stop > {
  static const char* value()
  {
    return "b2a9c605bb7a420089b02c6063322298";
  }

  static const char* value(const ::neo_msgs::Stop&) { return value(); }
};

template<>
struct DataType< ::neo_msgs::Stop > {
  static const char* value()
  {
    return "neo_msgs/Stop";
  }

  static const char* value(const ::neo_msgs::Stop&) { return value(); }
};


// service_traits::MD5Sum< ::neo_msgs::StopRequest> should match 
// service_traits::MD5Sum< ::neo_msgs::Stop > 
template<>
struct MD5Sum< ::neo_msgs::StopRequest>
{
  static const char* value()
  {
    return MD5Sum< ::neo_msgs::Stop >::value();
  }
  static const char* value(const ::neo_msgs::StopRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::neo_msgs::StopRequest> should match 
// service_traits::DataType< ::neo_msgs::Stop > 
template<>
struct DataType< ::neo_msgs::StopRequest>
{
  static const char* value()
  {
    return DataType< ::neo_msgs::Stop >::value();
  }
  static const char* value(const ::neo_msgs::StopRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::neo_msgs::StopResponse> should match 
// service_traits::MD5Sum< ::neo_msgs::Stop > 
template<>
struct MD5Sum< ::neo_msgs::StopResponse>
{
  static const char* value()
  {
    return MD5Sum< ::neo_msgs::Stop >::value();
  }
  static const char* value(const ::neo_msgs::StopResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::neo_msgs::StopResponse> should match 
// service_traits::DataType< ::neo_msgs::Stop > 
template<>
struct DataType< ::neo_msgs::StopResponse>
{
  static const char* value()
  {
    return DataType< ::neo_msgs::Stop >::value();
  }
  static const char* value(const ::neo_msgs::StopResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NEO_MSGS_MESSAGE_STOP_H
